### ISSUE TITLE
No black screen on resume from sleep/suspend

### ISSUE THREAD

**Issue by leewdch** [muennich/physlock#62] opened 2018-02-25 12:55 UTC
Version 11.
Sometime when I resume my laptop physlock is triggered without a black screen. Entering my password unlocks the pc but still there is a transparent background showing my workspace. The service is a systemd service of course and is triggered after sleep/suspend. What can I do to debug?

**Comment by muennich** [comment] 2018-02-25 19:06
Duplicate of issue #61.

**Closed by muennich** 2018-02-25 19:06 UTC
