### ISSUE TITLE
DPMS not applied when physlock is running

### ISSUE THREAD

**Issue by githububub** [muennich/physlock#37] opened 2016-07-13 18:02 UTC
No system suspend or hibernation. Running phylock both manually through terminal and via xautolock physlock in .xinitrc. xset dpms in .xinitrc.  DPMS does not apply when physlock is running = LED screen is on for hours when it can save energy in monitor standby/suspension.

**Comment by muennich** [comment] 2016-07-13 18:29
physlock uses a virtual terminal (/dev/ttyX) for the lock screen. X's DPMS settings have no effect there. Duplicate of issue #9.

**Closed by muennich** 2016-07-13 18:29 UTC
