### ISSUE TITLE
wrong password loop

### ISSUE THREAD

**Issue by x70b1** [muennich/physlock#86] opened 2019-12-13 09:11 UTC
I built physlock from the latest source. It seems to be broken.
The installation of `physlock` package on Arch is still working fine.

You have no chance to enter a password. Instead it shows in a loop the message that the password was wrong. The only way to fix it is to restart the device.

**Comment by muennich** [comment] 2019-12-16 08:30
This is possibly a duplicate of issue #72 and #80. Did you see those issues?

**Comment by x70b1** [comment] 2019-12-16 10:51
@muennich Thanks a lot! Thats what I can see.

The answer in the other issues seems to be that PAM is incorrectly configured.

But I use the exact same PAM config which I didn't change between the version from Arch `physlock` and `physlock-git`.

**Comment by muennich** [comment] 2019-12-16 11:17
How did you built it? Can you checkout and build tag v13 and see if it works?

**Comment by x70b1** [comment] 2019-12-17 20:28
Okay, I found my issue. The package `physlock-git` does not create a file in `/etc/pam.d/` while the official package `physlock` creates one.

For me the issue is fixed. Thanks for you help!
Or is here something to improve and we still need this issue?

**Comment by muennich** [comment] 2019-12-18 09:09
I have described the issue in a comment on the `physlock-git` AUR page, so that the pkg may get fixed.

**Closed by muennich** 2019-12-18 09:09 UTC
