### ISSUE TITLE
physlock v11 immediately enters infinite loop of authentication failed messages

### ISSUE THREAD

**Issue by pavlix** [muennich/physlock#60] opened 2018-02-14 13:45 UTC
Hi,

I have just built physlock for openSUSE Tumbleweed and I found a bug. When run whether from X11 terminal or VT it enters an infinite loop. The build I created might be wrong and miss important dependencies (see logs) but still if there is a failure, physlock should report an error, keep the machine unlocked and exit rather than locking it indefinitely and preventing authentication.

Cheers,

Pavel

https://build.opensuse.org/package/show/home:pavlix:Random/physlock

**Comment by muennich** [comment] 2018-02-14 14:27
What kind of infinite loop? Busy loop in the code or authentication failure after failure?

**Comment by muennich** [comment] 2018-02-14 18:45
Sorry for the hasty first reply. After reading the title and not only the comment I realized that this might be a duplicate of issue #47. The relevant part in that thread starts with my [second comment](https://github.com/muennich/physlock/issues/47#issuecomment-274006914). Please try that fix to see if it works for you too.

**Comment by muennich** [comment] 2018-03-10 19:31
Closing due to inactivity. Feel free to reopen if the mentioned fix does not work for you.

**Closed by muennich** 2018-03-10 19:31 UTC

**Comment by pavlix** [comment] 2018-07-02 12:42
Ack. This is a duplicate of #47.
